log:
  level: debug
inbounds:
  - listen: 0.0.0.0
    listen_port: 11023
    type: vless
    tag: vless-in
    users: [{ uuid: c5fdfb1f-df0d-4b93-a7a1-8051aeb27bf0 }]
    # wget -O mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64 && chmod +x ./mkcert
    # ./mkcert -cert-file cert.pem -key-file cert-key.pem aa.cc
    tls: { enabled: true, certificate_path: "./cert.pem", key_path: "./cert-key.pem" }
    multiplex: { enabled: true }
    transport: { type: ws, path: /streaming, max_early_data: 2048, early_data_header_name: Sec-WebSocket-Protocol }
  - listen: 0.0.0.0
    listen_port: 11024
    type: vmess
    tag: vmess-in
    users: [{ uuid: c5fdfb1f-df0d-4b93-a7a1-8051aeb27bf0, alterId: 0 }]
    tls: { enabled: true, certificate_path: "./cert.pem", key_path: "./cert-key.pem" }
    multiplex: { enabled: true }
    transport: { type: ws, path: /streaming, max_early_data: 2048, early_data_header_name: Sec-WebSocket-Protocol }
  - listen: 0.0.0.0
    listen_port: 11025
    type: vmess
    tag: http-in
    users: [{ uuid: c5fdfb1f-df0d-4b93-a7a1-8051aeb27bf0, alterId: 0 }]
    tls: { enabled: true, certificate_path: "./cert.pem", key_path: "./cert-key.pem" }
    multiplex: { enabled: true }
    transport: { type: http, path: /chatting, method: POST, idle_timeout: 15s, ping_timeout: 15s }
  - listen: 0.0.0.0
    listen_port: 29124
    type: hysteria2
    tag: hy2-in
    up_mbps: 1000
    down_mbps: 1000
    users: [{ password: c5fdfb1f-df0d-4b93-a7a1-8051aeb27bf0 }]
    tls: { enabled: true, certificate_path: "./cert.pem", key_path: "./cert-key.pem" }
outbounds:
  - { type: direct, tag: direct-out }
  #   官方客户端 https://pkg.cloudflareclient.com/
  # 或者
  #   第三方开源 MASQUE 实现
  #     $ wget -O usque https://github.com/Diniboy1123/usque/releases/download/v1.4.2/usque_1.4.2_linux_amd64.zip && sudo chmod +x ./usque
  #     $ ./usque register && ./usque socks -b 127.0.0.1 -p 1080 -d 1.1.1.1 -d 1.0.0.1 -d 2606:4700:4700::1111 -d 2606:4700:4700::1001
  # 或者
  #   用 docker 版本客户端
  #     $ docker run -d --name wasque --rm  -p 40000:40000 ghcr.io/diniboy1123/wasque:latest
  - { type: socks, tag: masque-out, server: warp, server_port: 40000 }
endpoints:
  # wget -O wgcf https://github.com/ViRb3/wgcf/releases/download/v2.2.29/wgcf_2.2.29_linux_amd64 && sudo chmod +x ./wgcf
  # ./wgcf register && ./wgcf generate
  - type: wireguard
    tag: wg-out
    mtu: 1280
    address: ["172.16.0.2/32", "2606:4700:110:88f3:7622:abea:ae90:2694/128"]
    private_key: "GCMpkutI+pUOs908dF27R3EM+8rFTtremeQsM2WkyHk="
    peers:
      - { address: engage.cloudflareclient.com, port: 2408, public_key: "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=", allowed_ips: ["0.0.0.0/0", "::/0"], reserved: [0, 0, 0] }
route:
  final: direct-out
  rules:
    # - { action: route, rule_set: [geosite-gemini], outbound: wg-out } # 解锁 gemini
    - { action: route, outbound: direct-out }
  rule_set:
    - { tag: geosite-gemini, type: remote, download_detour: direct-out, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google-gemini.json" }
    - { tag: geosite-google, type: remote, download_detour: direct-out, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google.json" }
    - { tag: geosite-youtube, type: remote, download_detour: direct-out, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/youtube.json" }
    - { tag: geosite-meta, type: remote, download_detour: direct-out, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/meta.json" }
    - { tag: geosite-ai, type: remote, download_detour: direct-out, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ai-!cn.json" }
