services:
  singbox:
    image: ghcr.io/sagernet/sing-box:v1.12.12
    ports:
      - 11023:11023
      - 11024:11024
      - 11025:11025
    volumes:
      - .:/singbox/conf
    command: run -D /singbox/conf
    restart: unless-stopped

  caddy:
    image: caddy:2.10.2-alpine
    ports:
      - 21180:80
      - 21433:443
      - 21433:443/udp
    volumes:
      - .:/etc/caddy
    restart: unless-stopped

  warp:
    profiles: [warp]
    image: ghcr.io/diniboy1123/wasque:2025.9.558.0
    ports:
      - 40000:40000
    restart: unless-stopped
